server:
  port: 8082
spring:
  shell:
    interactive:
      enabled: false
  datasource:
    initialization-mode: ALWAYS
    schema: classpath*:database/initDB.sql
    data: classpath*:database/populateDB.sql
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: 1240562Na
    driver-class-name: org.postgresql.Driver
    jpa:
      database: postresql
      database-platform: org.hibernate.dialect.PostreSQL10Dialect
